### ISSUE TITLE
Недописан метод mostPlayedByGenre

### ISSUE THREAD

**Issue by Kisulen** [Kisulen/JavaqaTeamDiplom#1]
# Описание 
В описании метода mostPlayerByGenre указано, что он должен принимать жанр и возвращать игру, в которую играли больше всего. Если в игру жанра не играли, возвращает null. Тело метода не содержит ничего, кроме {return null}.
**Примечание:** Неправильно поименован метод, но я не стану это выносить в отдельный баг-репорт. Должно быть mostPlayedByGenre. 

# Локация дефекта
Класс Player, последний метод
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/Player.java#L57-L61

# Шаги воспроизведения
 1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/Player.java#L57-L61) в IDEA
 2. В программе открыть класс Player 
 3.  Найти метод mostPlayerByGenre

*Ожидаемый результат:* Тело метода содержит логику, возвращающую игру, в которую играли больше всего, и логику при которой возвращается null.
*Фактический результат:* Тело метода содержит только {return null}. 

# Скриншот 
![image](https://user-images.githubusercontent.com/116299951/212426076-bc267ed8-c192-44fb-8ee1-1a0fc2c14d4a.png)

# Окружение 

- **Операционная система** Windows 10 Pro
- **IDE** IntelliJ IDEA Community edition 2022.2.3
- **Java** OpenJDK 11

**Comment by olganma** [comment]
Метод mostPlayedByGenre дописан. Тесты проходят.
