### ISSUE TITLE
Неполные требования к методу mostPlayedByGenre

### ISSUE THREAD

**Issue by Kisulen** [Kisulen/JavaqaTeamDiplom#2]
# Описание 
В описании метода mostPlayerByGenre не хватает информации о том, что должна делать программа, если несколько игр в рамках одного жанра имеют одинаковое количество часов, которое в них играли. 

# Локация дефекта
Класс Player, описание последнего метода
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/Player.java#L57-L58

# Шаги воспроизведения
 1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/Player.java#L57-L61) в IDEA
 2. В программе открыть класс Player 
 3.  Найти метод mostPlayerByGenre
 4. Прочитать описание того, что метод должен делать.

*Ожидаемый результат:* Описание метода содержит указание на то, что должна делать программа, если несколько игр в рамках одного жанра имеют одинаковое количество часов.
*Фактический результат:* Описание метода такой информации не содержит. 

# Скриншот 
![image](https://user-images.githubusercontent.com/116299951/212472740-1a5f54fe-ae9d-4174-894e-b0c18b25485a.png)

# Окружение 

- **Операционная система** Windows 10 Pro
- **IDE** IntelliJ IDEA Community edition 2022.2.3
- **Java** OpenJDK 11

**Comment by olganma** [comment]
Случай с одинаковым количеством часов по играм одного жанра можно не рассматривать.
