### ISSUE TITLE
В классе GameStore недописан метод getSumPlayedTime

### ISSUE THREAD

**Issue by olganma** [Kisulen/JavaqaTeamDiplom#3]
# Описание 
Метод getSumPlayedTime класса GameStore согласно требованиям должен суммировать общее количество времени всех игроков, проведённого за играми каталога. А код написан так, что метод будет всегда возвращать 0.
@Kisulen 

# Локация дефекта
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA
2. Открыть класс GameStore
3. Найти метод getSumPlayedTime

*Ожидаемый результат*: Метод возвращает общее количество времени всех игроков, проведённого за играми каталога.
*Фактический результат*: Метод возвращает 0.

# Скриншот
![image](https://user-images.githubusercontent.com/116002278/212496177-46b68190-850a-4b49-af5c-6a024b510f3b.png)

# Окружение
- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
- **Java:** OpenJDK 11

**Comment by Kisulen** [comment]
Метод дописан, тесты проходят
