### ISSUE TITLE
В методе play не происходит добавление проигранных часов к общему времени игры

### ISSUE THREAD

**Issue by Kisulen** [Kisulen/JavaqaTeamDiplom#4]
# Описание 
Согласно описанию, метод play должен записывать в коллекцию игрока обновленные значения для часов, проведенных за игрой, добавляя при этом новое значение. В метод это не включено, там только идёт запись в коллекцию значения, которое из неё же и достали.  Поскольку изначально в коллекции лежит 0, то туда перезаписывается 0, и метод нам всегда возвращает 0 для игр, которые уже были добавлены ранее в коллекцию. 

# Локация дефекта
Класс Player, метод play
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения
 1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/Player.java) в IDEA
 2. В программе открыть класс Player, прочитать описание метода play: он должен "обновить значения в мапе игрока, добавив проигранное количество часов". 
 3. на 36 строке (см. локация дефекта) видно, что в коллекцию игрока записывается игра и количество проигранных часов, которые берутся из коллекции же. 

*Ожидаемый результат:* в тестах при вызове метода play и передаче ему количества часов, он должен добавлять эти часы к имеющимся и выдавать сумму всех проигранных часов. 
*Фактический результат:* в тестах метод всегда отдает ноль. 

# Скриншот 
![image](https://user-images.githubusercontent.com/116299951/212560927-035b4ade-1ac6-47c0-8a6f-c892e4bd3f05.png)

# Окружение 

- **Операционная система** Windows 10 Pro
- **IDE** IntelliJ IDEA Community edition 2022.2.3
- **Java** OpenJDK 11

**Comment by olganma** [comment]
Изменения в строку 36 кода внесены. Метод play добавляет проигранные часы к имеющимся и выдает сумму общее время. Тесты проходят.
