### ISSUE TITLE
В методе play не реализовано требование о выводе RuntimeException

### ISSUE THREAD

**Issue by Kisulen** [Kisulen/JavaqaTeamDiplom#5]
# Описание 
В описании метода play содержится требование выкидывать RunTimeException если игра не была установлена. Данное требование в методе не реализовано.  

# Локация дефекта
Класс Player, метод play
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/Player.java#L32-L41

# Шаги воспроизведения
 1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/Player.java) в IDEA
 2. В программе открыть класс Player 
 3.  Найти метод play
 4. Прочитать его и убедиться, что в теле метода нигде не указано, когда вызывать RunTimeException. 

*Ожидаемый результат:* Тело метода содержит логику, вызывающую RunTimeException, если игра не была установлена.
*Фактический результат:* Тело метода не содержит такой логики. 

# Скриншот 
![image](https://user-images.githubusercontent.com/116299951/212501231-b883627e-e698-4e29-87b7-ec06ff1a1de8.png)

# Окружение 

- **Операционная система** Windows 10 Pro
- **IDE** IntelliJ IDEA Community edition 2022.2.3
- **Java** OpenJDK 11

**Comment by olganma** [comment]
Исключение RunTimeException в соответствии с требованием в метод play добавлено.
