### ISSUE TITLE
Метод containsGame возвращает false при наличии 1 игры в каталоге

### ISSUE THREAD

**Issue by olganma** [Kisulen/JavaqaTeamDiplom#6]
# Описание 
Согласно требованиям метод containsGame класса GameStore должен проверять наличие игры в каталоге и возврашать true, если игра есть. А когда в список игр каталога добавлена всего одна игра, то метод containsGame возвращает false.

# Локация дефекта
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения
1. Открыть [проект](https://github.com/Kisulen/JavaqaTeamDiplom) в IDEA 
2. Открыть класс GameStore
3. Найти метод containsGame
4. Перейти в класс GameStoreTest
5. Найти тест shouldAddGame
6. На последней строке кода теста (со сравнением) поставить BreakPoint
7. Запустить отладчик
8. Перейти до проверки строки кода метода containsGame с условием в цикле for 

*Ожидаемый результат*: Условие завершения цикла в методе containsGame возвращает true.
*Фактический результат*: Условие завершения цикла в методе containsGame возвращает false.

# Скриншот
![image](https://user-images.githubusercontent.com/116002278/212554088-cf6eaf66-e679-442a-94b9-394707e997b9.png)

# Окружение
- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
- **Java:** Open

**Comment by Kisulen** [comment]
Ошибка в коде исправлена. В секции условия меньше (<) заменено на (<=), так как при одной добавленной игре размер коллекции равен единице, и условие с "меньше" не выполнялось. 
Тесты проходят.
