### ISSUE TITLE
Метод install ни на что не влияет в коде

### ISSUE THREAD

**Issue by Kisulen** [Kisulen/JavaqaTeamDiplom#7]
# Описание 
В класс Player включен метод install, который однако ни на что не влияет в коде. Формально он записывает игру в коллекцию playedtime класса Player, и по идее должен вызываться в начале метода play, чтобы без установки игры невозможно было в неё сыграть. 

# Локация дефекта
Класс Player, метод play - в нём отсутствует условие, использующее метод install. 
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения
 1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/Player.java) в IDEA
 2. В программе открыть класс Player 
 3. Запустить тест, который проходит на данном этапе и использует метод play. Убедиться, что тест проходит. 
 4.  В тесте shouldOnlyInstallGame (или в любом другом тесте, который проходит на данном этапе) закомментировать строку, содержащую метод install.
 5. Запустить тест в таком виде и убедиться, что он по-прежнему проходит. 

*Ожидаемый результат:* При выключении метода install в тесте, где содержится метод play, тест должен падать.
*Фактический результат:* Тест проходит одинаково успешно как с методом install, так и без него. 

# Скриншот 
Тест с включенным методом install
![image](https://user-images.githubusercontent.com/116299951/212555044-c8319b17-210b-4018-9d7a-e39b97b57b64.png)
Тест с выключенным методом install
![image](https://user-images.githubusercontent.com/116299951/212555234-62241b27-8736-4ab8-904c-beab0660d02d.png)

# Окружение 

- **Операционная система** Windows 10 Pro
- **IDE** IntelliJ IDEA Community edition 2022.2.3
- **Java** OpenJDK 11

**Comment by olganma** [comment]
После добавления в метод play логики с RunTimeException, метод install стал в коде влиять. Без установки игры невозможно в неё сыграть. Тесты это подтвердили.
