### ISSUE TITLE
Метод addPlayTime не регистрирует общее количество времени игрока за игрой каталога

### ISSUE THREAD

**Issue by olganma** [Kisulen/JavaqaTeamDiplom#8]
# Описание 
Метод addPlayTime класса GameStore согласно требованиям должен регистрировать количество времени, которое проиграл игрок за игрой каталога. При этом время должно суммироваться с прошлым значением для этого игрока.
А с текущим кодом, если игрок ранее в игру каталога играл, метод будет регистрировать только прошлое время (ранее сохраненное).

# Локация дефекта
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/GameStore.java#L48

# Шаги воспроизведения
1. Открыть [проект](https://github.com/Kisulen/JavaqaTeamDiplom) в IDEA
2. Открыть класс GameStore
3. Найти метод addPlayTime

*Ожидаемый результат*: Метод регистрирует общее количество времени игрока, проведённого за играми каталога.
*Фактический результат*: Метод возвращает прошлое количество времени игрока, проведенного за играми каталога.

# Скриншот
![image](https://user-images.githubusercontent.com/116002278/212561840-3927494f-97b7-4268-9e90-20bb8b4c06dc.png)

# Окружение
- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2022.2.3 (Community Edition)
- **Java:** Open

**Comment by Kisulen** [comment]
Метод исправлен, тесты проходят. 
на 48 строке к уже записанному в коллекцию времени теперь прибавляется количество часов, переданное в параметрах метода.
