### ISSUE TITLE
Неполное покрытие кода в методе play при проверке в JaCoCo

### ISSUE THREAD

**Issue by Kisulen** [Kisulen/JavaqaTeamDiplom#9]
# Описание 
При проверке тестового покрытия кода в классе Player через плагин JaCoCo обнаружено, что одна строка в методе play никогда не используется, так как условие, необходимое для запуска кода по else не выполняется никогда. 

# Локация дефекта
Класс Player,метод play
https://github.com/Kisulen/JavaqaTeamDiplom/blob/4fc543cf689a37b93d514e04d97846d507c5b07c/src/main/java/ru/netology/Player.java#L38

# Шаги воспроизведения
 1. Открыть [код программы](https://github.com/Kisulen/JavaqaTeamDiplom/blob/main/src/main/java/ru/netology/Player.java) в IDEA
 2. Запустить тесты в классе PlayerTest
 3. Убедиться, что все тесты проходят
 4. Запустить плагин JaCoCo, перейти в отчёт
 5. Строка 35 жёлтая - значит одно из условий не покрыто тестами
 6. Строка 38 красная - её условие никогда не вызывается, поэтому этот код никогда не исполняется. 
 
*Ожидаемый результат:* После проведения анализа программы с применением техник тест-дизайна все строки кода должны быть зелёными
*Фактический результат:* Есть жёлтая строка, где одно из условий в if не исполняется, и красная строка, потому что её условие никогда не вызывается. 
# Скриншот 
![image](https://user-images.githubusercontent.com/116299951/212694982-8bf79945-49dc-41bc-9135-e148a4a3fdfd.png)

# Окружение 

- **Операционная система** Windows 10 Pro
- **IDE** IntelliJ IDEA Community edition 2022.2.3
- **Java** OpenJDK 11

**Comment by olganma** [comment]
Исправлено условие в коде метода. Тесты проходят.
